export const GET_ERRORS = 'GET_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const DOWNLOAD_SET_DATA = 'DOWNLOAD_SET_DATA';
export const DOWNLOAD_CLEAR_DATA = 'DOWNLOAD_CLEAR_DATA';
export const DOWNLOAD_LINK_ADD = 'DOWNLOAD_LINK_ADD';
export const DOWNLOAD_LOADING = 'DOWNLOAD_LOADING';
